on:
  push:
    branches: [master]

jobs:
  semantic-release:
    name: "Semantic release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: "Release with semantic-release"
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
